### ISSUE TITLE
compatibility is missing (not running on windows)

### ISSUE THREAD

**Issue by ahaeberle** [raguay/OpenWithEditor#1]
@raguay this is only a documentation issue and ment to be found by other fman-windows-users. 

Thanks for your investmend of a good plugin!

the readme and the source code only implicit mentions this as a macOS only plugin, hence alfred and bitbar are not available on winOS or linux.

this is in fact an design fault by fman itself, but could be easily solved by adding a note to the README.md

As I have written in https://github.com/fman-users/fman/issues/638 the plugin may easily be rewritten to give some basic functions on windows - considering the fact, that the .myeditorconfig might be no good place on windows itself.

**Comment by raguay** [comment]
I added a disclaimer on the README.md file for the plugin and added `macOS` to the tags for the repository. I'm sorry if it was a little bit confusing, but I assumed only people using BitBar or TextBar would be interested in using this plugin. I do use it on Linux, but I create the needed file myself. I currently don't have access to a functional Windows system or testing.
